### ISSUE TITLE
Not showing up in vscode

### ISSUE THREAD

**Issue by jughn** [Pinperepette/pirate-flat#1]
After cloning the repo in `.vscode/extensions` folder and restarting vscode it does not show up in the list of available themes.
Steps to reproduce:
- VSCode v.1.83.1 on MacOS Monterey 12.7
- Clone the repo using the provided command 
- Restart VSCode
- Open the theme picker (cmd+k, cmd+t)

I checked the folder (`.vscode/extensions/pirate-flat`) and tried to `git pull`, shows Already up to date.
Also there is no specific error/warning in VSCode Developer Tools.

**Comment by Pinperepette** [comment]
I'm sorry . I truly appreciate your patience as I work to resolve this issue. I've made attempts to make modifications based on the feedback, but pinpointing the exact problem has proven challenging, especially because the extension is working without issues on my end across various platforms.

I assure you I am actively investigating this matter and trying different approaches to identify and fix the underlying problem. If you have any specific details about the issue you're facing or any error messages you've encountered, please share them with me. Any additional information you can provide will be immensely helpful in diagnosing and resolving the problem.

Thank you for your understanding and cooperation as I work to resolve this issue. Your input is invaluable in this process

**Comment by Pinperepette** [comment]
I have added the VSIX file for the theme in the repository. You can install it using the 'Install from VSIX' option in Visual Studio Code. Just select the newly added VSIX file, and it will go through the automatic installation process. If you need any assistance, feel free to ask

**Comment by jughn** [comment]
Pulling the latest update from main branch fixed the issue. Now the theme shows up in the list. 
Thank you very much for your help and your work!
